import { describe, expect, it } from 'vitest';
import {
  ARTIFACT_MSA_LOCAL_WORK_BUDGET,
  ARTIFACT_MSA_MAX_ALIGNMENTS,
  ARTIFACT_MSA_MAX_CELLS,
  ARTIFACT_MSA_MAX_COLUMNS,
  ARTIFACT_MSA_MAX_LOCAL_SEQUENCES,
  ARTIFACT_MSA_MAX_IMPORT_CHARACTERS,
  ARTIFACT_MSA_MAX_NAME_LENGTH,
  ARTIFACT_MSA_MAX_ROWS,
  ARTIFACT_MSA_MAX_WORKSPACE_CELLS,
  ArtifactAlignmentError,
  artifactAlignmentResult,
  clampMsaClientPoint,
  createLocalArtifactAlignment,
  estimateLocalAlignmentWork,
  formatAlignedFasta,
  formatClustal,
  formatConsensusFasta,
  normalizeArtifactAlignment,
  normalizeArtifactAlignments,
  msaColumnFromClientX,
  msaEdgeAutoScrollDelta,
  parseAlignmentText,
  parseAlignedFasta,
  safeAlignmentFilename,
  serializeArtifactAlignment,
  type ArtifactAlignmentInput,
  type ArtifactMsaRecord,
} from '../claude-science-msa';

function expectAlignmentError(run: () => unknown, code: ArtifactAlignmentError['code']): void {
  try {
    run();
    throw new Error(`Expected ArtifactAlignmentError(${code})`);
  } catch (error) {
    expect(error).toBeInstanceOf(ArtifactAlignmentError);
    expect(error).toMatchObject({ code });
  }
}

function rows(count: number, sequence: string, prefix = 'row') {
  return Array.from({ length: count }, (_, index) => ({
    id: `${prefix}-${index + 1}`,
    name: `${prefix} ${index + 1}`,
    aligned: sequence,
  }));
}

describe('Claude Science alignment drag geometry', () => {
  it('clamps an out-of-bounds pointer just inside the viewport', () => {
    expect(clampMsaClientPoint(480, -20, {
      left: 100,
      right: 420,
      top: 40,
      bottom: 240,
    })).toEqual({ clientX: 419.5, clientY: 40 });
  });

  it('scales edge auto-scroll with overshoot and caps the per-frame speed', () => {
    expect(msaEdgeAutoScrollDelta(50, 50, 250)).toBe(0);
    expect(msaEdgeAutoScrollDelta(45, 50, 250)).toBe(-2);
    expect(msaEdgeAutoScrollDelta(270, 50, 250)).toBe(7);
    expect(msaEdgeAutoScrollDelta(500, 50, 250)).toBe(32);
  });

  it('maps clamped client coordinates to the newly scrolled edge column', () => {
    const metrics = {
      viewportLeft: 100,
      viewportRight: 500,
      labelWidth: 160,
      scrollLeft: 300,
      cellWidth: 10,
      columnCount: 120,
    };
    expect(msaColumnFromClientX(700, metrics)).toBeNull();
    expect(msaColumnFromClientX(700, metrics, true)).toBe(53);
    expect(msaColumnFromClientX(0, metrics, true)).toBe(30);
  });
});

describe('Claude Science alignment normalization', () => {
  it('parses ordinary aligned FASTA while normalizing BOMs, comments, dots, whitespace, and case', () => {
    const alignment = parseAlignedFasta(
      '\uFEFF; generated by an external aligner\r\n>  Alpha  \r\nacg.t\r\n\r\n>Beta\r\nA C G-T\r\n',
      {
        id: 'demo alignment',
        name: 'Imported demo',
        molecule: 'dna',
        engine: { id: 'mafft', label: 'MAFFT', version: '7.526', mode: 'local-command' },
      },
    );

    expect(alignment).toMatchObject({
      id: 'demo-alignment',
      name: 'Imported demo',
      molecule: 'dna',
      alignmentLength: 5,
      referenceRowId: 'row-1',
      engine: { id: 'mafft', label: 'MAFFT', version: '7.526', mode: 'local-command' },
    });
    expect(alignment.rows.map(({ name, aligned }) => ({ name, aligned }))).toEqual([
      { name: 'Alpha', aligned: 'ACG-T' },
      { name: 'Beta', aligned: 'ACG-T' },
    ]);
  });

  it('requires a real FASTA header and equal-length aligned rows', () => {
    expectAlignmentError(() => parseAlignedFasta('ACGT\n>Beta\nACGT'), 'invalid_fasta');
    expectAlignmentError(() => parseAlignedFasta('>\nACGT\n>Beta\nACGT'), 'invalid_fasta');
    expectAlignmentError(() => parseAlignedFasta('>Alpha\nACGT\n>Beta\nACG--'), 'invalid_alignment');
    expectAlignmentError(() => normalizeArtifactAlignment({ rows: 'not-an-array' } as unknown), 'invalid_alignment');
    expectAlignmentError(() => normalizeArtifactAlignment({
      molecule: 'misc',
      rows: rows(2, 'ACGT'),
    } as unknown), 'invalid_alignment');
    expectAlignmentError(() => normalizeArtifactAlignment({
      rows: rows(2, 'ACGT'),
      engine: { mode: 'native' },
    } as unknown), 'invalid_alignment');
  });

  it('rejects duplicate row names case-insensitively and duplicate row ids', () => {
    expectAlignmentError(() => normalizeArtifactAlignment({
      rows: [
        { id: 'one', name: 'Alpha', aligned: 'ACGT' },
        { id: 'two', name: 'alpha', aligned: 'ACGT' },
      ],
    }), 'invalid_alignment');

    expectAlignmentError(() => normalizeArtifactAlignment({
      rows: [
        { id: 'same', name: 'Alpha', aligned: 'ACGT' },
        { id: 'same', name: 'Beta', aligned: 'ACGT' },
      ],
    }), 'invalid_alignment');

    expectAlignmentError(() => normalizeArtifactAlignment({
      referenceRowId: 'missing',
      rows: [
        { id: 'one', name: 'Alpha', aligned: 'ACGT' },
        { id: 'two', name: 'Beta', aligned: 'ACGT' },
      ],
    }), 'invalid_alignment');

    expectAlignmentError(() => normalizeArtifactAlignment({
      rows: [
        { name: 'Alpha', aligned: '----' },
        { name: 'Beta', aligned: 'ACGT' },
      ],
    }), 'invalid_alignment');
  });

  it('rejects row and alignment names that could inject extra FASTA records', () => {
    expectAlignmentError(() => normalizeArtifactAlignment({
      name: 'review\n>forged-alignment',
      molecule: 'dna',
      rows: rows(2, 'ACGT'),
    }), 'invalid_alignment');
    expectAlignmentError(() => normalizeArtifactAlignment({
      molecule: 'dna',
      rows: [
        { name: 'Alpha\n>forged-row', aligned: 'ACGT' },
        { name: 'Beta', aligned: 'ACGT' },
      ],
    }), 'invalid_alignment');
  });

  it('enforces the declared molecule alphabet instead of silently changing molecule type', () => {
    expectAlignmentError(() => normalizeArtifactAlignment({
      molecule: 'dna',
      rows: [
        { name: 'Alpha', aligned: 'ACGT' },
        { name: 'Beta', aligned: 'ACGX' },
      ],
    }), 'invalid_alignment');

    expectAlignmentError(() => normalizeArtifactAlignment({
      molecule: 'rna',
      rows: [
        { name: 'Alpha', aligned: 'ACGU' },
        { name: 'Beta', aligned: 'ACGT' },
      ],
    }), 'invalid_alignment');

    expect(normalizeArtifactAlignment({
      molecule: 'protein',
      rows: [
        { name: 'Alpha', aligned: 'MKT-*' },
        { name: 'Beta', aligned: 'MKR-?' },
      ],
    }).molecule).toBe('protein');

    expectAlignmentError(() => normalizeArtifactAlignment({
      rows: [
        { name: 'Ambiguous A', aligned: 'MART' },
        { name: 'Ambiguous B', aligned: 'MATT' },
      ],
    }), 'invalid_alignment');

    expectAlignmentError(() => normalizeArtifactAlignment({
      rows: [
        { name: 'DNA', aligned: 'ACGT' },
        { name: 'RNA', aligned: 'ACGU' },
      ],
    }), 'invalid_alignment');
  });

  it('computes majority consensus, strict conservation, gap-only columns, and row identity', () => {
    const alignment = normalizeArtifactAlignment({
      id: 'summary',
      molecule: 'dna',
      rows: [
        { id: 'a', name: 'Alpha', aligned: 'A-CGT' },
        { id: 'b', name: 'Beta', aligned: 'ATCGT' },
        { id: 'c', name: 'Gamma', aligned: 'AG-GT' },
      ],
    });

    expect(alignment.consensus).toBe('AGCGT');
    expect(alignment.conserved).toEqual([true, false, false, true, true]);
    expect(alignment.gapOnly).toEqual([false, false, false, false, false]);
    expect(alignment.rows.map((row) => row.identity)).toEqual([80, 80, 80]);

    const withGapColumns = normalizeArtifactAlignment({
      molecule: 'dna',
      rows: [
        { name: 'Alpha', aligned: 'A--' },
        { name: 'Beta', aligned: 'A--' },
      ],
    });
    expect(withGapColumns.consensus).toBe('A--');
    expect(withGapColumns.gapOnly).toEqual([false, true, true]);
    expect(withGapColumns.conserved).toEqual([true, false, false]);
    expect(withGapColumns.rows.map((row) => row.identity)).toEqual([100, 100]);
  });

  it('rejects row, column, cell, alignment-count, workspace-cell, and text limits transactionally', () => {
    expect({
      alignments: ARTIFACT_MSA_MAX_ALIGNMENTS,
      rows: ARTIFACT_MSA_MAX_ROWS,
      columns: ARTIFACT_MSA_MAX_COLUMNS,
      cells: ARTIFACT_MSA_MAX_CELLS,
      workspaceCells: ARTIFACT_MSA_MAX_WORKSPACE_CELLS,
    }).toEqual({ alignments: 50, rows: 100, columns: 50_000, cells: 2_000_000, workspaceCells: 4_000_000 });

    expectAlignmentError(() => normalizeArtifactAlignment({ rows: rows(ARTIFACT_MSA_MAX_ROWS + 1, 'A') }), 'too_large');
    expectAlignmentError(() => normalizeArtifactAlignment({
      rows: rows(2, 'A'.repeat(ARTIFACT_MSA_MAX_COLUMNS + 1)),
    }), 'too_large');
    expectAlignmentError(() => normalizeArtifactAlignment({
      rows: rows(ARTIFACT_MSA_MAX_ROWS, 'A'.repeat(Math.floor(ARTIFACT_MSA_MAX_CELLS / ARTIFACT_MSA_MAX_ROWS) + 1)),
    }), 'too_large');
    expectAlignmentError(() => normalizeArtifactAlignment({
      name: 'n'.repeat(ARTIFACT_MSA_MAX_NAME_LENGTH + 1),
      molecule: 'dna',
      rows: rows(2, 'A'),
    }), 'too_large');

    expectAlignmentError(
      () => parseAlignedFasta(`>Alpha\n${'A'.repeat(ARTIFACT_MSA_MAX_IMPORT_CHARACTERS)}\n>Beta\nA`, { molecule: 'dna' }),
      'too_large',
    );

    const tiny = (index: number): ArtifactAlignmentInput => ({ id: `alignment-${index}`, molecule: 'dna', rows: rows(2, 'A', `tiny-${index}`) });
    expectAlignmentError(
      () => normalizeArtifactAlignments(Array.from({ length: ARTIFACT_MSA_MAX_ALIGNMENTS + 1 }, (_, index) => tiny(index))),
      'too_large',
    );

    const maxCellRows = (prefix: string) => rows(100, 'A'.repeat(20_000), prefix);
    expectAlignmentError(() => normalizeArtifactAlignments([
      { id: 'large-a', molecule: 'dna', rows: maxCellRows('a') },
      { id: 'large-b', molecule: 'dna', rows: maxCellRows('b') },
      { id: 'over-the-workspace-limit', molecule: 'dna', rows: rows(2, 'A', 'c') },
    ]), 'too_large');
  });

  it('rejects duplicate saved alignment ids', () => {
    expectAlignmentError(() => normalizeArtifactAlignments([
      { id: 'duplicate', molecule: 'dna', rows: rows(2, 'A', 'a') },
      { id: 'duplicate', molecule: 'dna', rows: rows(2, 'A', 'b') },
    ]), 'invalid_alignment');
  });
});

describe('Claude Science bounded local alignment', () => {
  const record = (id: string, sequence: string, type: ArtifactMsaRecord['type'] = 'dna'): ArtifactMsaRecord => ({
    id,
    name: id.toUpperCase(),
    sequence,
    type,
  });

  it('estimates dynamic-programming work before running and preserves record provenance on success', () => {
    expect(estimateLocalAlignmentWork([record('a', 'AA'), record('b', 'AAA')])).toBe(12);

    const alignment = createLocalArtifactAlignment([
      record('a', 'ATGC'),
      record('b', 'ATGT'),
      record('c', 'ATGG'),
    ], { id: 'local', name: 'Local preview', createdAt: '2026-07-12T00:00:00.000Z' });

    expect(alignment).toMatchObject({
      id: 'local',
      name: 'Local preview',
      molecule: 'dna',
      engine: {
        id: 'motif-star',
        label: 'Motif local preview',
        mode: 'browser',
        usedFallback: false,
      },
      createdAt: '2026-07-12T00:00:00.000Z',
    });
    expect(alignment.rows.map((row) => row.sourceRecordId)).toEqual(['a', 'b', 'c']);
    expect(alignment.note).toMatch(/computed locally in this browser/i);
  });

  it('requires 2–10 records of one molecule type within the sequence and work budgets', () => {
    expect(ARTIFACT_MSA_MAX_LOCAL_SEQUENCES).toBe(10);
    expect(ARTIFACT_MSA_LOCAL_WORK_BUDGET).toBe(40_000_000);

    expectAlignmentError(() => createLocalArtifactAlignment([record('only', 'ACGT')]), 'invalid_alignment');
    expectAlignmentError(() => createLocalArtifactAlignment([
      record('dna', 'ACGT', 'dna'),
      record('protein', 'MKTQ', 'protein'),
    ]), 'mixed_molecule');
    expectAlignmentError(() => createLocalArtifactAlignment([
      record('a', 'A'.repeat(3_001)),
      record('b', 'A'.repeat(3_001)),
    ]), 'too_large');
    expectAlignmentError(() => createLocalArtifactAlignment(
      Array.from({ length: ARTIFACT_MSA_MAX_LOCAL_SEQUENCES + 1 }, (_, index) => record(`r${index}`, 'ACGT')),
    ), 'invalid_alignment');
    expectAlignmentError(() => createLocalArtifactAlignment([
      record('a', 'A'.repeat(3_000)),
      record('b', 'A'.repeat(3_000)),
      record('c', 'A'.repeat(3_000)),
    ]), 'work_budget');
  });
});

describe('Claude Science alignment handoff formats', () => {
  const alignment = normalizeArtifactAlignment({
    id: 'handoff',
    name: 'Alpha / Beta comparison',
    molecule: 'dna',
    referenceRowId: 'alpha',
    rows: [
      { id: 'alpha', name: 'Alpha', aligned: 'ACGTAC', sourceRecordId: 'record-a', inputSha256: 'sha-a' },
      { id: 'beta', name: 'Beta', aligned: 'ACGTTC', sourceRecordId: 'record-b', inputSha256: 'sha-b' },
    ],
    engine: {
      id: 'mafft',
      label: 'MAFFT',
      mode: 'local-command',
      version: '7.526',
      parameters: ['--auto'],
      usedFallback: false,
    },
    createdAt: '2026-07-12T00:00:00.000Z',
    outputSha256: 'output-sha',
    note: 'Imported after a verified command-line run.',
  });

  it('exports aligned FASTA, CLUSTAL blocks, and consensus FASTA', () => {
    expect(formatAlignedFasta(alignment)).toBe('>Alpha\nACGTAC\n>Beta\nACGTTC\n');
    expect(formatConsensusFasta(alignment)).toBe('>Alpha / Beta comparison consensus\nACGTAC\n');

    const clustal = formatClustal(alignment, 4);
    expect(clustal).toMatch(/^CLUSTAL W multiple sequence alignment\n\n/);
    expect(clustal).toContain('Alpha       ACGT');
    expect(clustal).toContain('Beta        ACGT');
    expect(clustal).toMatch(/\n\s+\*\*\*\*\n/);
    expect(clustal).toContain('Alpha       AC');
    expect(clustal).toContain('Beta        TC');
  });

  it('writes unique whitespace-safe CLUSTAL identifiers and re-imports its own .aln output', () => {
    const longNames = normalizeArtifactAlignment({
      name: 'Long labels',
      molecule: 'dna',
      rows: [
        { name: 'sample alpha with a very long shared prefix one', aligned: 'ACGT-A' },
        { name: 'sample alpha with a very long shared prefix two', aligned: 'ACGCTA' },
      ],
    });
    const clustal = formatClustal(longNames, 4);
    const identifiers = clustal.split('\n')
      .filter((line) => /^\S+\s+[A-Z*?.-]+(?:\s+\d+)?\s*$/.test(line))
      .slice(0, 2)
      .map((line) => line.trim().split(/\s+/)[0]);

    expect(identifiers).toHaveLength(2);
    expect(new Set(identifiers).size).toBe(2);
    expect(identifiers.every((identifier) => /^[A-Za-z0-9_.-]{1,30}$/.test(identifier))).toBe(true);
    const restored = parseAlignmentText(clustal, { name: 'Restored CLUSTAL', molecule: 'dna' });
    expect(restored.rows.map((row) => row.aligned)).toEqual(longNames.rows.map((row) => row.aligned));
    expect(restored.rows.map((row) => row.name)).toEqual(identifiers);
  });

  it('serializes a restorable alignment without smuggling derived arrays into durable data', () => {
    const serialized = serializeArtifactAlignment(alignment);
    expect(serialized).toEqual({
      id: 'handoff',
      name: 'Alpha / Beta comparison',
      molecule: 'dna',
      referenceRowId: 'alpha',
      rows: [
        { id: 'alpha', name: 'Alpha', aligned: 'ACGTAC', sourceRecordId: 'record-a', inputSha256: 'sha-a' },
        { id: 'beta', name: 'Beta', aligned: 'ACGTTC', sourceRecordId: 'record-b', inputSha256: 'sha-b' },
      ],
      engine: {
        id: 'mafft', label: 'MAFFT', mode: 'local-command', version: '7.526', parameters: ['--auto'], usedFallback: false,
      },
      createdAt: '2026-07-12T00:00:00.000Z',
      outputSha256: 'output-sha',
      note: 'Imported after a verified command-line run.',
    });
    expect(serialized).not.toHaveProperty('consensus');
    expect(serialized).not.toHaveProperty('conserved');
    expect(normalizeArtifactAlignment(serialized)).toMatchObject({
      consensus: alignment.consensus,
      conserved: alignment.conserved,
      gapOnly: alignment.gapOnly,
      alignmentLength: alignment.alignmentLength,
      centerIdx: alignment.centerIdx,
    });

    if (typeof serialized.engine !== 'string' && serialized.engine?.parameters) serialized.engine.parameters[0] = '--changed';
    expect(alignment.engine.parameters).toEqual(['--auto']);
  });

  it('creates defensive MSA results and safe download names', () => {
    const result = artifactAlignmentResult(alignment);
    expect(result).toMatchObject({
      consensus: 'ACGTAC',
      alignmentLength: 6,
      centerIdx: 0,
    });
    result.rows[0].aligned = 'mutated';
    result.conserved[0] = false;
    expect(alignment.rows[0].aligned).toBe('ACGTAC');
    expect(alignment.conserved[0]).toBe(true);
    expect(safeAlignmentFilename(alignment, '.aligned.fasta')).toBe('alpha-beta-comparison.aligned.fasta');
  });
});
